global:
  scrape_interval:     5s
  evaluation_interval: 5s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'process-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['process-exporter:9256']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'caddy'
    scrape_interval: 5s
    static_configs:
      - targets: ['caddy:2019']

  - job_name: 'vnstat'
    scrape_interval: 30s
    static_configs:
      - targets: ['vnstati:8685']

  - job_name: 'docker-exporter'
    scrape_interval: 2m
    scrape_timeout: 1m
    static_configs:
      - targets: ['docker-exporter:9100']

#  - job_name: 'prominence'
#    scrape_interval: 2s
#    static_configs:
#      - targets: ['prominence:25585']


alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'
